
USE_CAMERA_STUB := false

# Inherit from the proprietary version if exists
-include vendor/huawei/u8800pro/BoardConfigVendor.mk

# Platform
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
#ARCH_ARM_HAVE_NEON :=true

TARGET_BOARD_PLATFORM := msm7x30
#TARGET_BOARD_PLATFORM := msm7630_surf
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_BOOTLOADER_BOARD_NAME := u8800pro

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
TARGET_GRALLOC_USES_ASHMEM := true
COMMON_GLOBAL_CFLAGS += -DHAVE_ARM_TLS_REGISTER
COMMON_GLOBAL_CFLAGS += -DTARGET_MSM7x30
BOARD_USE_SKIA_LCDTEXT := true

# Audio
#BOARD_PROVIDES_LIBAUDIO := true
BOARD_USES_STEREO_HW_SPEAKER :=true
BOARD_USES_QCOM_AUDIO_CALIBRATION :=true
BOARD_USES_QCOM_AUDIO_SPEECH := true
BOARD_USES_QCOM_AUDIO_LPA :=true
BOARD_USES_QCOM_AUDIO_VOIPMUTE :=true
BOARD_USES_QCOM_AUDIO_RESETALL :=true

# RIL
BOARD_PROVIDES_LIBRIL := true

# Graphics
DCHECK_FOR_EXTERNAL_FORMAT := true
USE_OPENGL_RENDERER := true
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60 -DQCOM_HARDWARE
TARGET_USES_C2D_COMPOSITION := true
TARGET_HAVE_BYPASS := false
TARGET_USES_OVERLAY := true
TARGET_FORCE_CPU_UPLOAD := true
BOARD_USES_QCNE := true
TARGET_USES_SF_BYPASS := false
WEBCORE_INPAGE_VIDEO := true
TARGET_HAVE_TSLIB := true
BOARD_EGL_CFG := device/huawei/u8800pro/egl.cfg

WITH_JIT := true
ENABLE_JSC_JIT := true
JS_ENGINE := v8
HTTP := chrome
ENABLE_WEBGL = true

# Kernel
TARGET_PREBUILT_KERNEL := device/huawei/u8800pro/kernel
#TARGET_PREBUILT_RECOVERY_KERNEL := device/huawei/u8800pro/kernel

BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=huawei
BOARD_INSTALLER_CMDLINE := $(BOARD_KERNEL_CMDLINE)
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096

# Wifi
WIFI_BOARD_NAME_HUAWEI := true 
WPA_SUPPLICANT_VERSION := VER_0_8_X
HOSTAPD_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_wext
BOARD_WLAN_DEVICE := bcm4329
WIFI_DRIVER_MODULE_PATH     := "/system/wifi/dhd.ko"
WIFI_DRIVER_FW_PATH_STA     := "/system/wifi/firmware.bin"
WIFI_DRIVER_FW_PATH_AP      := "/system/wifi/firmware_apsta.bin"
WIFI_DRIVER_MODULE_NAME     :=  "dhd"
WIFI_DRIVER_MODULE_ARG      :=  "firmware_path=/system/wifi/firmware.bin nvram_path=/system/wifi/nvram.txt"

# Sensors
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := u8800pro
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_GPS_LIBRARIES := libloc_api

# FM
BOARD_HAVE_FM_RADIO := true
BOARD_FM_DEVICE := bcm4329
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO -DFM_RADIO

# File System
TARGET_USERIMAGES_USE_EXT4 := true

#BOARD_MMC_DEVICE := /dev/block/mmcblk0
#BOARD_DATA_DEVICE := /dev/block/mmcblk0p13
#BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p14
#BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1p1
#BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p2

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x04200000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x05300000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 264634368 #256MB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 274464768 #1GB
BOARD_PERSISTIMAGE_PARTITION_SIZE := 5242880 #5MB
BOARD_CACHEIMAGE_PARTITION_SIZE := 134217728 #128MB
BOARD_TOMBSTONESIMAGE_PARTITION_SIZE := 4096000 #4000KB
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
BOARD_CUSTOM_GRAPHICS := ../../../device/huawei/u8800pro/recovery/graphics.c
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_10x18.h\"
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_TOUCH_RECOVERY := true

# Custom releasetools for old partition table.
TARGET_PROVIDES_RELEASETOOLS := true
TARGET_RELEASETOOL_OTA_FROM_TARGET_SCRIPT := ./device/huawei/u8800pro/releasetools/ota_from_target_files
#TARGET_CUSTOM_RELEASETOOL := device/huawei/u8800pro/tools/releasetools
# ETC
TARGET_SPECIFIC_HEADER_PATH := device/huawei/u8800pro/include

TARGET_COMPRESS_MODULE_SYMBOLS := false
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
BOARD_ALWAYS_INSECURE := true
