#!/bin/sh

# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

VENDOR=huawei
DEVICE=u8800pro
BASE=../../../vendor/$VENDOR/$DEVICE/proprietary

rm -rf $BASE/*

adb start-server
echo "Waiting for device..."
adb wait-for-device

while read FILE
do
	DIR=`dirname $FILE`
	if [ ! -d $BASE/$DIR ]; then
		mkdir -p $BASE/$DIR
	fi
	adb pull /system/$FILE $BASE/$FILE
done < proprietary-files.txt

chmod 775 $BASE/bin/*
chmod 644 $BASE/lib/*
chmod 777 $BASE/lib/egl
chmod 644 $BASE/lib/egl/*

./setup-makefiles.sh

